### ISSUE TITLE
[DataCap Application]  mty - kepler 

### ISSUE THREAD

**Issue by yann-y** [VenusOfficial/Pathway-VFDA#10]
### Version

1

### DataCap Applicant

yann

### Project ID

1

### Data Owner Name

NOAA

### Data Owner Country/Region

American Samoa

### Data Owner Industry

Environment

### Website

https://www.mty.wang

### Social Media Handle

yann

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

100TiB

### Expected size of single dataset (one copy)

20TiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

100TiB

### On-chain address for first allocation

f1y76bzdmdczpghobjemia7rathc2vb2wg2aywopi

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Team: MTYW Team

Maitian Yunwang (Hangzhou) Information Technology Co., Ltd. was established in 2020 and is a high-tech enterprise specializing in distributed data storage. It is a new force and driving force in the national new infrastructure construction team. The company takes identity authentication technology as its security infrastructure and building a distributed storage architecture as its technical roadmap, committed to independent research and application of trusted private cloud technology. The company's services are based on the Maitian Cloud Network distributed private cloud platform, utilizing advanced technologies such as big data and cloud computing to integrate government and enterprise business data, monitoring data, operational data, etc., to provide customers with end-to-end intelligent value-added services, driven by data.


Project: Distributed Cloud Storage（ https://www.mty.wang/data-storage ）

MNStar is a storage system independently developed by Maitian Cloud Network based on the architecture design and operational experience of object storage services. It is a stable, reliable, high-performance, and flexible elastic computing service provided by Maitian Cloud Network to customers. Customers can create and use cloud servers according to different business needs at any time, saving a lot of time and cost compared to IT hardware, while simplifying IT procurement, deployment, implementation, operation and maintenance work. Capable of building hundreds of EB level highly reliable, secure, low-cost, and scalable business systems for customers to meet diverse unstructured data storage needs.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data stored in Filecoin is from publicly available datasets with important information for environments via NOAA.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
There will be more regional storage service providers.
We use go-graphsplit to split a large dataset into graph slices to make deals.
storage and retrieval use droplet
```

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-ndfd/
s3://noaa-ndfd-pds/
https://registry.opendata.aws/noaa-cdr-terrestrial/
s3://noaa-cdr-leaf-area-index-fapar-pds/
https://registry.opendata.aws/noaa-cdr-atmospheric/
s3://noaa-cdr-aerosol-optical-thickness-pds/
https://registry.opendata.aws/noaa-ndfd/
https://registry.opendata.aws/noaa-ufs-s2s/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1. f01934215, lijiang
2. f01904929, Wuzhen
3. f02057286, US
4. f01915051, hangzhou
5. f01901765, China
```

### How do you plan to make deals to your storage providers

Droplet client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by VenusOfficial** [comment]
Resubmission from #5 .

**Comment by VenusOfficial** [comment]
checker:manualTrigger

**Comment by yann-y** [comment]
checker:manualTrigger

**Comment by yann-y** [comment]
checker:manualTrigger

**Comment by yann-y** [comment]
checker:manualTrigger

**Comment by yann-y** [comment]
checker:manualTrigger

**Comment by VenusOfficial** [comment]
The robot seems to be not working.
Based on [this](https://datacapstats.io/clients?filter=+f1y76bzdmdczpghobjemia7rathc2vb2wg2aywopi) result temporarily.

**Comment by yann-y** [comment]
checker:manualTrigger

**Comment by yann-y** [comment]
checker:manualTrigger

**Comment by yann-y** [comment]
checker:manualTrigger

**Comment by VenusOfficial** [comment]
good job

**Comment by VenusOfficial** [comment]
<img width="1095" alt="image" src="https://github.com/VenusOfficial/Pathway-VFDA/assets/155081686/de56041d-381a-4c6d-b1ac-e5ee753118e2">
**This client is currently using 40T, but the signature panel shows that the balance is insufficient (there should be 60T left).**
<img width="1418" alt="image" src="https://github.com/VenusOfficial/Pathway-VFDA/assets/155081686/1924b6ed-690b-4b6c-9990-317a88ce932b">

**Comment by VenusOfficial** [comment]
The above error have not been resolved yet, It is recommended that the applicant manually close the application.
If still wish to obtain Datacaps via this pathway, please resubmit.

**Comment by yann-y** [comment]
The [bug](https://github.com/fidlabs/allocator-tooling/issues/50) has been resolved.

**Comment by VenusOfficial** [comment]
<img width="667" alt="image" src="https://github.com/user-attachments/assets/768c816e-dde8-47f0-873e-b1872a009de2">

**Comment by ipfsforcezuofu** [comment]
checker:manualTrigger

**Comment by kevzak** [comment]
@VenusOfficial why did you close this application with DataCap still remaining?

**Comment by kevzak** [comment]
checker:manualTrigger

**Comment by VenusOfficial** [comment]
> @VenusOfficial why did you close this application with DataCap still remaining?

@kevzak Some issues were identified in the client's data. After an offline discussion with the client, we agreed to close the application with the remaining DC.
