### ISSUE TITLE
[DataCap Application] <Jinshi Asset management> - <sitedata1>

### ISSUE THREAD

**Issue by whymichaelgu1** [VenusOfficial/Pathway-VFDA#14]
### Data Owner Name

jinshi asset management

### Data Owner Country/Region

China

### Data Owner Industry

Financial Services

### Website

https://www.jinshizichan.cn/

### Social Media Handle

michael

### Social Media Type

Slack

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

200TiB

### Expected size of single dataset (one copy)

50TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

50TiB

### On-chain address for first allocation

f1sshymsne7x3cndwflpk57ozerlzkxgzv7aknadq

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Shanghai Jinshizichan Asset Management Co., Ltd. was established in November 2015 with a registered capital of 14 million USD. The company specializes  on management of non-performing assets. The company is registered in Shanghai, and has set up Qingdao headquarters, Beijing branch, Shanghai branch, Shenzhen branch and  Nanjing branch and other regional operation services. The main business focuses on Shanghai, Beijing, Qingdao, Shenzhen, Yangtze River Delta and Pearl River Delta. Adhering to the basic principles of safety, efficiency, rapid realization and asset revitalization, we are committed to build a one-stop service platform for special asset disposal .The company has talented  teams in project development, resource integration, due diligence, risk control, asset disposal and other areas, the team members are mainly composed of financial institutions, AMC, practicing lawyers, auditors, accountants and other professionals. Today, the company has established close cooperative relations with many well-known domestic service institutions.
At present, the assets under management exceeds 200 million USD. 
The business scope of the Shanghai Jinshizichan Asset management is composed of:
1. Acquisition and disposal of non-performing assets
2. Enterprise debt restructuring
3. Asset foreclosure sales services

The data storage project is mostly about Acquisition and disposal of non-performing assets.
Acquisition and disposal of non-performing assets mainly provides acquisition and disposal services for non-performing loan business generated by banks, trusts, funds, small loans and other licensed financial institutions. Among many financial businesses, real estate, land and commercial mortgage assets are the mainstream assets in the acquisition and disposal of non-performing businesses.
Banks, trusts, small loans and other licensed financial institutions engaged in financial services, special enterprise financing loans, there are a large number of real estates, commercial, industrial land and other property mortgage financial business, in recent years affected by the macroeconomic environment, the non-performing assets of financial industry has increased rapidly. In order to quickly recover capital, reduce losses, and meet regulatory requirements, financial institutions have a large number of disposal needs for non-performing assets.
At present, the main asset classes that Jinshizichan Asset Management focuses on are high-quality non-performing assets such as residential mortgages, commercial and industrial. The data we would like to store on fiecoin network mostly derived from information Collection, due diligence and asset disposal part of the business operation.
1. Information Collection. Through information collection and channel recommendation, collect information from financial institutions
2. Asset due diligence. Through its legal team and accountant team, Jinshizichan Asset Management conducts full due diligence on assets, including asset appraisal, debt relationship combing, asset preservation investigation, debtor interview, legal risk investigation, asset market recommendation, etc. 
3. Asset disposal. After obtaining the asset package, Jinshizichan will negotiate with the debtor to repurchase and settle, transfer creditor's rights or apply to the court through a lawyer to auction the collateral online to execute the payment.
Jinshizichan will perform due diligence over 1 billion USD worth of assets per year, which will generate a large number of due diligence data of assets and properties. The main form of due diligence data is videos and pictures of the assets.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
Jinshizichan will perform due diligence over 1 billion USD worth of assets per year, which will generate a large number of due diligence data of assets and properties. The main form of due diligence data is videos and pictures of the assets.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
We will use graphsplit
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No
```

### Please share a sample of the data

```text
https://drive.google.com/file/d/1O0MNhaeSQfS_Z0JpEhfDmWcsmzYhuc_p/view?usp=share_link
https://drive.google.com/file/d/1g8nWui6nuUuuV6d8IRFlYQjsi0gaR6Ab/view?usp=share_link
https://drive.google.com/file/d/1q77ntrrW2YXPecax5W3TA36wQtfY8SFs/view?usp=share_link
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [x] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1. f02368987, USA
2. f02812251, USA
3. f01901765, China
4. f02932299, China
```

### How do you plan to make deals to your storage providers

Droplet client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by VenusOfficial** [comment]
Glad to receive your application.
The applicant has had multiple offline communications with me in last year, confirm their true existence.

There are two questions, please confirm: @whymichaelgu1 
1. The dataset is marked as private commercial/enterprise, does it support public retrieval?
2. What is the relationship between the data sample and this dataset (this client)?

**Comment by VenusOfficial** [comment]
The client has resubmitted #15 , this application is closed.
