### ISSUE TITLE
[DataCap Application] <6block> - <noaa>

### ISSUE THREAD

**Issue by echoof** [VenusOfficial/Pathway-VFDA#24]
### Data Owner Name

NOAA

### Data Owner Country/Region

American Samoa

### Data Owner Industry

Environment

### Website

https://6block.com/

### Social Media Handle

echo

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

800TiB

### Expected size of single dataset (one copy)

200TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

200TiB

### On-chain address for first allocation

f1txhkzfvmq3qbqpzebmfcesytrvkuxklpx7vmcma

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
First place in Filecoin Space Race,
Global mine layout, distributed in Asia, Europe, America, etc.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data comes from NOAA's open data
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
go-graphsplit
```

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-nam/
https://registry.opendata.aws/noaa-nbm/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

Less than 1 year

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f03141858 HK
f03141860 HK
f03141867 xinjiang
f03141872 xinjiang
```

### How do you plan to make deals to your storage providers

Droplet client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by VenusOfficial** [comment]
The issue was closed on Jun 26.
