### ISSUE TITLE
[DataCap Application] <Weitu tech> - <dev/op data>

### ISSUE THREAD

**Issue by wangchen138** [VenusOfficial/Pathway-VFDA#26]
### Data Owner Name

WEITU

### Data Owner Country/Region

China

### Data Owner Industry

IT & Technology Services

### Website

N/A

### Social Media Handle

N/A

### Social Media Type

WeChat

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

2PiB

### Expected size of single dataset (one copy)

500TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

500TiB

### On-chain address for first allocation

f16zongsonw7kjii75vsqmoapvvupf7xdh52ptvaa

### Data Type of Application

Private Commercial/Enterprise

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We leverage our parent company's expertise in computer hardware and software infrastructure design to establish ourselves as a leading provider of professional computer technology services, a manufacturer of blockchain products, and a distributor of electronic commercial display solutions. We are actively engaged in blockchain technology research and employ cutting-edge methods to integrate blockchain computing into devices like smart homes and HVAC equipment. By harnessing the power of idle devices through specialized computing modules, we enhance our computational capabilities while keeping costs minimal. Furthermore, we offer remote monitoring software for these blockchain devices, ensuring a secure and efficient control system. Our philosophy is rooted in professionalism and excellence, evident in our diverse range of intelligent commercial display products and integrated solutions that cater to the TV and surveillance industries.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
DEV DATA
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

None

### If you are not preparing the data, who will prepare the data?  (Provide name and business)

```text
regional data will send to sp they will process
```

### Please share a sample of the data

```text
https://drive.google.com/file/d/17zB2loGKl8ou3JuMjYSbm5SIsG1xT4c9/view?usp=sharing

https://drive.google.com/file/d/1H5jU2bvAxS9cdn7WK7Y9hTP5guiC6V_t/view?usp=sharing

https://drive.google.com/file/d/1yd6WpiFFTMjAyTnMCEv0yDN11a6sMNNH/view?usp=sharing
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [ ] I confirm

### What is the expected retrieval frequency for this data

Yearly

### For how long do you plan to keep this dataset stored on Filecoin

More than 3 years

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server, IPFS, Lotus built-in data transfer, Venus built-in data transfer

### How did you find your storage providers

Slack, Filmine, Big Data Exchange, Partners, Others

### Please list the provider IDs and location of the storage providers you will be working with.

```text
f02980903 KR
f03079511 HK
will disclose in comment when sps are ready
```

### How do you plan to make deals to your storage providers

Boost client, Lotus client, Singularity

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by VenusOfficial** [comment]
As mentioned earlier, we cannot offer you 2 PiB, I'll only start maximum of 1 PiB now.

**Comment by VenusOfficial** [comment]
I will track the follow-up report and look forward to better work. Up.

**Comment by wangchen138** [comment]
adding one node for this tranche from KR: f02980903

**Comment by VenusOfficial** [comment]
The 1P DC requirement has been fulfilled. It can be closed.
