### ISSUE TITLE
[DataCap Application] mtyw - kepler

### ISSUE THREAD

**Issue by yann-y** [VenusOfficial/Pathway-VFDA#5]
### Version

1

### DataCap Applicant

yann

### Project ID

1

### Data Owner Name

NOAA

### Data Owner Country/Region

American Samoa

### Data Owner Industry

Environment

### Website

https://www.mty.wang/home

### Social Media Handle

yann

### Social Media Type

Slack

### What is your role related to the dataset

data preparer

### Total amount of DataCap being requested

100

### Unit for total amount of DataCap being requested

TiB

### Expected size of single dataset (one copy)

20

### Unit for expected size of single dataset

TiB

### Number of replicas to store

5

### Weekly allocation of DataCap requested

100TiB

### Unit for weekly allocation of DataCap requested

TiB

### On-chain address for first allocation

f1ros77tqminx2v5ni3ley526333m3rdj7gg43hna

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
Team: MTYW Team

Maitian Yunwang (Hangzhou) Information Technology Co., Ltd. was established in 2020 and is a high-tech enterprise specializing in distributed data storage. It is a new force and driving force in the national new infrastructure construction team. The company takes identity authentication technology as its security infrastructure and building a distributed storage architecture as its technical roadmap, committed to independent research and application of trusted private cloud technology. The company's services are based on the Maitian Cloud Network distributed private cloud platform, utilizing advanced technologies such as big data and cloud computing to integrate government and enterprise business data, monitoring data, operational data, etc., to provide customers with end-to-end intelligent value-added services, driven by data.


Project: Distributed Cloud Storage（ https://www.mty.wang/data-storage ）

MNStar is a storage system independently developed by Maitian Cloud Network based on the architecture design and operational experience of object storage services. It is a stable, reliable, high-performance, and flexible elastic computing service provided by Maitian Cloud Network to customers. Customers can create and use cloud servers according to different business needs at any time, saving a lot of time and cost compared to IT hardware, while simplifying IT procurement, deployment, implementation, operation and maintenance work. Capable of building hundreds of EB level highly reliable, secure, low-cost, and scalable business systems for customers to meet diverse unstructured data storage needs.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
The data stored in Filecoin is from publicly available datasets with important information for environments via NOAA.
```

### Where was the data currently stored in this dataset sourced from

AWS Cloud

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

There will be more regional storage service providers.
We use [go-graphsplit](https://github.com/filedrive-team/go-graphsplit) to split a large dataset into graph slices to make deals.
storage and retrieval use [droplet](https://github.com/ipfs-force-community/droplet)

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

Increase the number of replicas and storage cycles

### Please share a sample of the data

```text
https://registry.opendata.aws/noaa-ndfd/
s3://noaa-ndfd-pds/
https://registry.opendata.aws/noaa-cdr-terrestrial/
s3://noaa-cdr-leaf-area-index-fapar-pds/
https://registry.opendata.aws/noaa-cdr-atmospheric/
s3://noaa-cdr-aerosol-optical-thickness-pds/
https://registry.opendata.aws/noaa-ndfd/
https://registry.opendata.aws/noaa-ufs-s2s/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Weekly

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3)

### How did you find your storage providers

Slack

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1. f01934215, lijiang
2. f01904929, Wuzhen
3. f02057286, US
4. f01915051, hangzhou
5. f01901765, China
```

### How do you plan to make deals to your storage providers

Droplet client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by VenusOfficial** [comment]
The applicant is a data preparer, please supplement or correct the above information: @yann-y 
1. Please modify the relevant entries, including "Project Name", "DataCap Application", "role", "Total amount and Number of replicas"
2、If you are a data preparer. What is your location (Country/Region)
3、If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?
4、If you are not preparing the data, who will prepare the data? (Provide name and business)
5、Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.
6、How do you plan to make deals to your storage providers？
7、Can you confirm that you will follow the Fil+ guideline？

**Comment by yann-y** [comment]
Please recheck.

**Comment by VenusOfficial** [comment]
- As VFDA pathway is still in its early stages and this is the first application, please modify the total amount of dc be requested to 100 TiB.
- Please change your role related to dataset to 'data preparer'.

**Comment by yann-y** [comment]
ok，complete.

> * As VFDA pathway is still in its early stages and this is the first application, please modify the total amount of dc be requested to 100 TiB.
> * Please change your role related to dataset to 'data preparer'.
