### ISSUE TITLE
[DataCap Application] <Yitu> - <encode-public>

### ISSUE THREAD

**Issue by ldoublewood** [VenusOfficial/Pathway-VFDA#7]
### Version

1

### DataCap Applicant

Guilin Yitu Network Technology Co., Ltd.

### Project ID

01

### Data Owner Name

ENCODE Data Coordinating Center

### Data Owner Country/Region

United States

### Data Owner Industry

Life Science / Healthcare

### Website

https://www.etu1314.com/

### Social Media Handle

tiger

### Social Media Type

Slack

### What is your role related to the dataset

Data Preparer

### Total amount of DataCap being requested

500TiB

### Expected size of single dataset (one copy)

1024TiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

300TiB

### On-chain address for first allocation

f1bowd7pk75b3hv4yegl4dpdt3rd55uks7q4h7gsq

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [ ] Use Custom Multisig

### Share a brief history of your project and organization

```text
We are specialized to assist Filecoin SP(Storage Provider) to store meaningful Data on Filecoin.
```

### Is this project associated with other projects/ecosystem stakeholders?

No

### Describe the data being stored onto Filecoin

```text
They are all open and useful datasets that can be obtained publicly, .e.g. from Open Data on AWS. This application involves the following datasets:
1. Encyclopedia of DNA Elements (ENCODE)

for detail of above datasets:
1. The Encyclopedia of DNA Elements (ENCODE) Consortium is an international collaboration of research groups funded by the National Human Genome Research Institute (NHGRI). The goal of ENCODE is to build a comprehensive parts list of functional elements in the human genome, including elements that act at the protein and RNA levels, and regulatory elements that control cells and circumstances in which a gene is active. ENCODE investigators employ a variety of assays and methods to identify functional elements. The discovery and annotation of gene elements is accomplished primarily by sequencing a diverse range of RNA sources, comparative genomics, integrative bioinformatic methods, and human curation. Regulatory elements are typically investigated through DNA hypersensitivity assays, assays of DNA methylation, and immunoprecipitation (IP) of proteins that interact with DNA and RNA, i.e., modified histones, transcription factors, chromatin regulators, and RNA-binding
```

### Where was the data currently stored in this dataset sourced from

My Own Storage Infra

### If you are a data preparer. What is your location (Country/Region)

China

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
graphsplit
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
not yet
```

### Please share a sample of the data

```text
the sample can be accessed via aws cli command as below (aws cli tool should be installed beforehand):
aws s3 ls --no-sign-request s3://encode-public/
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Sporadic

### For how long do you plan to keep this dataset stored on Filecoin

1 to 1.5 years

### In which geographies do you plan on making storage deals

Greater China

### How will you be distributing your data to storage providers

HTTP or FTP server

### How did you find your storage providers

Slack, Partners

### Please list the provider IDs and location of the storage providers you will be working with.

```text
1. f02886969，Nemeng China
2. f02930544, Nemeng China
3. f02931712, Fushan China
4. f02932299, Zhengzhou China
```

### How do you plan to make deals to your storage providers

Droplet client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by VenusOfficial** [comment]
Please modify and confirm the following content
- Expected size of single dataset (one copy)
- Number of replicas to store
- Weekly allocation of DataCap requested

**Comment by ldoublewood** [comment]
> Please modify and confirm the following content
> 
> * Expected size of single dataset (one copy)
> * Number of replicas to store
> * Weekly allocation of DataCap requested
Hi, I have filled the reply in the original application post as below,  why I need to modify and confirm?

Expected size of single dataset (one copy)
1024TiB

Number of replicas to store
4

Weekly allocation of DataCap requested
300TiB

**Comment by VenusOfficial** [comment]
For the first time, 100T will be allocated.

**Comment by ldoublewood** [comment]
Hi, we have used about 100T datacap,  what should we do to continue?  What is the meaning of 'Refill"?

**Comment by VenusOfficial** [comment]
checker:manualTrigger

**Comment by VenusOfficial** [comment]
> Hi, we have used about 100T datacap, what should we do to continue? What is the meaning of 'Refill"?

'Refill' refers to the allocation of a new round of quotas.

**Comment by VenusOfficial** [comment]
⚠️ Not supported for retrieval, this dataset should support retrieval;
⚠️ Lack of dispersion, only distributed on a single node;
⚠️ Data sharing, sealed data that is not promised;

Confirm that the client is cheating and immediately close this application.

**Comment by kevzak** [comment]
checker:manualTrigger
